export const USER_OPTIONS_POPOVER_OFFSET = 8;
export const USER_OPTIONS_POPOVER_AVATAR_OFFSET = 4;
export const USER_OPTIONS_POPOVER_OFFSET_COMPACT = 2;
export const USER_OPTIONS_POPOVER_NESTED_OFFSET = 12;
